#spring boot 开发环境下 配置文件
server:
  port: 80
  context-path: /exam
spring:
  datasource:
    dirver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/examination?characterEncoding=utf8&useSSL=true
    username: root
    password: ironman2014
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  redis:
    host: 118.89.25.207
    password: echo0.cn




#七牛云
qiniu:
  ak: q23-t4WJ9DuDNkAt3N1gLcWMLpQ5ScJNFjGqBWzG
  sk: GNTiRex64QsnUeSJgFC99oMCWbNUhVuOJbT_ELbC
  bucket: lan-store
  path: p7f7rr200.bkt.clouddn.com